{{- if not .Values.cloudConfigSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{ include "capi-cloudstack.cloudConfigSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
stringData:
  api-key: {{ (required ".Values.cloudConfigSecret.apiKey must be set"
        .Values.cloudConfigSecret.apiKey) }}
  secret-key: {{ (required ".Values.cloudConfigSecret.secretKey must be set"
        .Values.cloudConfigSecret.secretKey) }}
  api-url: {{ (required ".Values.cloudConfigSecret.apiUrl must be set"
        .Values.cloudConfigSecret.apiUrl) }}
  verify-ssl: {{ .Values.cloudConfigSecret.verifySSL }}
{{- end -}}
